PRODUCTS = [
    {
        "id": "cl-aurora-watch",
        "name": "Aurora X1 Smart Watch",
        "category": "Wearables",
        "price": 249.0,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
        "description": "A titanium smart watch with health telemetry, week-long battery life, sapphire glass and adaptive workout coaching.",
        "features": ["ECG-ready biosensors", "7 day battery", "AMOLED always-on display", "5 ATM water resistance"],
    },
    {
        "id": "cl-sonicbuds-pro",
        "name": "SonicBuds Pro",
        "category": "Audio",
        "price": 179.0,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
        "description": "Spatial audio earbuds with adaptive ANC, studio-grade microphones and a compact wireless charging case.",
        "features": ["Adaptive noise cancellation", "Low latency gaming mode", "36 hour case battery", "Multipoint pairing"],
    },
    {
        "id": "cl-nova-laptop",
        "name": "NovaBook Air 14",
        "category": "Computing",
        "price": 1199.0,
        "rating": 4.9,
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
        "description": "A thin creator laptop with a 3K display, all-day battery and AI-assisted thermal performance.",
        "features": ["3K color accurate panel", "32 GB unified memory", "1 TB NVMe storage", "Aluminum unibody"],
    },
    {
        "id": "cl-focus-camera",
        "name": "FocusFrame 8K Camera",
        "category": "Creator Gear",
        "price": 899.0,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
        "description": "Mirrorless 8K camera with in-body stabilization, cinematic color profiles and creator-friendly wireless transfer.",
        "features": ["8K open gate capture", "Dual native ISO", "7-stop stabilization", "Wi-Fi studio sync"],
    },
    {
        "id": "cl-pulse-speaker",
        "name": "PulseDock Speaker",
        "category": "Audio",
        "price": 329.0,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80",
        "description": "Room-filling smart speaker dock with beamforming audio, home automation controls and lossless streaming.",
        "features": ["360 degree soundstage", "Matter smart home hub", "Lossless Wi-Fi audio", "Voice privacy switch"],
    },
    {
        "id": "cl-vertex-tablet",
        "name": "Vertex Pro Tablet",
        "category": "Computing",
        "price": 749.0,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80",
        "description": "A pro tablet for sketching, notes and field work with a laminated display and detachable keyboard support.",
        "features": ["120 Hz laminated display", "Magnetic pencil dock", "Desktop-class browser", "Face unlock"],
    },
]
